// 41 Topics from Term Store Management
export const SECONDARY_TOPICS = [
  { value: 'approving_authorities', label: 'Approving Authorities' },
  { value: 'awards_recognition', label: 'Awards & Recognition' },
  { value: 'business_continuity_planning', label: 'Business Continuity Planning' },
  { value: 'career_transition', label: 'Career Transition' },
  { value: 'compensation', label: 'Compensation' },
  { value: 'competencies', label: 'Competencies' },
  { value: 'conduct_discipline', label: 'Conduct & Discipline' },
  { value: 'confirmation', label: 'Confirmation' },
  { value: 'crisis_management', label: 'Crisis Management' },
  { value: 'data_management_governance', label: 'Data Management & Governance' },
  { value: 'deployment', label: 'Deployment' },
  { value: 'employee_records', label: 'Employee Records' },
  { value: 'employee_wellbeing', label: 'Employee Wellbeing' },
  { value: 'flexible_work_arrangements', label: 'Flexible Work Arrangements' },
  { value: 'hr_analytics', label: 'HR Analytics' },
  { value: 'hr_management', label: 'HR Management' },
  { value: 'hrp_system', label: 'HRP System' },
  { value: 'industrial_relations', label: 'Industrial Relations' },
  { value: 'internship', label: 'Internship' },
  { value: 'leadership_development', label: 'Leadership Development' },
  { value: 'learning', label: 'Learning' },
  { value: 'leave_benefits', label: 'Leave Benefits' },
  { value: 'leaving_service', label: 'Leaving Service' },
  { value: 'medical_dental_benefits', label: 'Medical & Dental Benefits' },
  { value: 'medical_board', label: 'Medical Board' },
  { value: 'mentoring_coaching', label: 'Mentoring & Coaching' },
  { value: 'organisational_design', label: 'Organisational Design' },
  { value: 'other_benefits', label: 'Other Benefits' },
  { value: 'our_future_workforce', label: 'Our Future Workforce' },
  { value: 'psc_scholarships', label: 'PSC Scholarships' },
  { value: 'performance_management', label: 'Performance Management' },
  { value: 'personnel_board_system', label: 'Personnel Board System' },
  { value: 'recruitment_appointment', label: 'Recruitment & Appointment' },
  { value: 'restructuring_exercise', label: 'Restructuring Exercise' },
  { value: 're_employment', label: 'Re-Employment' },
  { value: 'security_screening', label: 'Security Screening' },
  { value: 'service_injury', label: 'Service Injury' },
  { value: 'strategic_workforce_planning', label: 'Strategic Workforce Planning' },
  { value: 'superannuation', label: 'Superannuation' },
  { value: 'transport_travel', label: 'Transport & Travel' },
  { value: 'values', label: 'Values' },
] as const;

// 25 Primary Topics for Access Control
export const PRIMARY_TOPICS = [
  { value: 'business_continuity_planning', label: 'Business Continuity Planning' },
  { value: 'hr_analytics', label: 'HR Analytics' },
  { value: 'organisational_design', label: 'Organisational Design' },
  { value: 'public_service_transformation', label: 'Public Service Transformation' },
  { value: 'internship', label: 'Internship' },
  { value: 'psc_scholarships', label: 'PSC Scholarships' },
  { value: 'recruitment_appointment', label: 'Recruitment & Appointment' },
  { value: 'deployment', label: 'Deployment' },
  { value: 'learning_growth', label: 'Learning & Growth' },
  { value: 'performance_management', label: 'Performance Management' },
  { value: 'talent_management_development', label: 'Talent Management & Development' },
  { value: 'compensation', label: 'Compensation' },
  { value: 'conduct_discipline', label: 'Conduct & Discipline' },
  { value: 'employee_recognition_wellbeing', label: 'Employee Recognition & Wellbeing' },
  { value: 'flexible_work_arrangements', label: 'Flexible Work Arrangements' },
  { value: 'industrial_relations', label: 'Industrial Relations' },
  { value: 'leave', label: 'Leave' },
  { value: 'medical', label: 'Medical' },
  { value: 'transport_travel', label: 'Transport & Travel' },
  { value: 'other_benefits', label: 'Other Benefits' },
  { value: 'leaving_service', label: 'Leaving Service' },
  { value: 're_employment', label: 'Re-Employment' },
  { value: 'general', label: 'General' },
  { value: 'personnel_board_matters', label: 'Personnel Board Matters' },
  { value: 'approving_authorities', label: 'Approving Authorities' },
  { value: 'data_systems', label: 'Data & Systems' },
] as const;

// Content Groups for Access Control
export const CONTENT_GROUPS = [
  { value: 'hrl_cs', label: 'HRL Civil Service' },
  { value: 'hrl_sb', label: 'HRL Statutory Board' },
  { value: 'hro_cs', label: 'HR Ops Civil Service' },
  { value: 'hro_sb', label: 'HR Ops Statutory Board' },
] as const;

// Applicable For options (audience targeting)
export const APPLICABLE_FOR_OPTIONS = [
  { value: 'cs_only', label: 'Civil Service Only' },
  { value: 'cs_and_sb', label: 'Civil Service & Statutory Boards' },
] as const;

// Circular Types for Access Control
export const CIRCULAR_TYPES = [
  { value: 'hrl', label: 'HRL Circulars' },
  { value: 'hr_ops', label: 'HR Operations Circulars' },
] as const;

export const RESOURCE_CATEGORY_TYPES = [
  { value: 'advice', label: 'Advice' },
  { value: 'agreement', label: 'Agreement' },
  { value: 'article', label: 'Article' },
  { value: 'calendar', label: 'Calendar' },
  { value: 'circular', label: 'Circular' },
  { value: 'faq', label: 'FAQ' },
  { value: 'form', label: 'Form' },
  { value: 'guide', label: 'Guide' },
  { value: 'internal', label: 'Internal' },
  { value: 'legislation', label: 'Legislation' },
  { value: 'link', label: 'Link' },
  { value: 'list', label: 'List' },
  { value: 'media', label: 'Media' },
  { value: 'report', label: 'Report' },
  { value: 'sharing', label: 'Sharing' },
  { value: 'slides', label: 'Slides' },
  { value: 'speech', label: 'Speech' },
  { value: 'template', label: 'Template' },
] as const;
